# .github/workflows/lint.yml

name: Code check # name of the action (displayed in the github interface)

on: # event list
  push:
  pull_request: # on a pull request to each of these branches
    branches:
      - master

env: # environment variables (available in any part of the action)
  NODE_VERSION: 22.17.0

jobs: # list of things to do
  eslint:
    name: Eslint check # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Eslint
        run: npm run lint

      - name: Stylelint
        run: npm run lint:style

  typescript:
    name: Typescript check
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Typescript
        run: npm run typescript
